# Site settings
title: Human Centered Computing
email: wiese@cs.utah.edu
description: "Human-Centered Computing at SoC, University of Utah"
baseurl: ""#"http://www.cs.utah.edu/~wiese/hcc"
url: ""#"http://www.cs.utah.edu/~wiese/hcc"
twitter_username:
github_username: 
youtube_username:
facebook_page:
license_url:
safe: false
lsi: false
google_analytics: "'UA-69348306-1'"
use_analytics: true

paper_content_url: http://hcc.utah.edu/papers/



# Build settings
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty
sass:
  sass_dir: _sass
# exclude from build
exclude: ["README.md", "Rakefile", "changelog.md", ".idea/", "Gemfile", "Gemfile.lock", "rvm.env"]

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  persons:
    output: false
    permalink: /persons/:path/
  publications:
    output: true
    permalink: /publications/:path/
  thesis:
    output: true
    permalink: /thesis/:path/
  videos:
    output: false
    permalink: /videos/:path/
  datasets:
    output: false
    permalink: /datasets/:path/
  institutions:
    output: false
    permalink: /institutions/:path/
  funding:
    output: false
    permalink: /funding/:path/
